name: Build Debian package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-debpkg-debian-trixie:
    strategy:
      fail-fast: false

    runs-on: debian

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc libssl-dev debhelper devscripts fakeroot

      - name: Build
        run: |
          export DEBFULLNAME="ZiYuan Yang"
          export DEBEMAIL="yzymc@yzynetwork.org"
          dch --local '+trixie' "Build for Debian Trixie" -D trixie
          dpkg-buildpackage -us -uc

      - name: Copy
        run: |
          mkdir output
          cp ../fy4dec_* output/
          cp ../fy4dec-dbgsym_* output/

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: fy4dec-debpkg-debian-trixie
          path: output/
          if-no-files-found: error

  build-debpkg-ubuntu-noble:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          export DEBFULLNAME="ZiYuan Yang"
          export DEBEMAIL="yzymc@yzynetwork.org"
          sudo apt update
          sudo apt install -y build-essential gcc libssl-dev debhelper devscripts fakeroot

      - name: Build
        run: |
          dch --local '+noble' "Build for Ubuntu Noble" -D noble
          dpkg-buildpackage -us -uc

      - name: Copy
        run: |
          mkdir output
          cp ../fy4dec_* output/
          cp ../fy4dec-dbgsym_* output/

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: fy4dec-debpkg-ubuntu-noble
          path: output/
          if-no-files-found: error