name: Build Debian package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-debpkg:
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian
          - ubuntu-latest

    runs-on: ${{ matrix.distro }}

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc libssl-dev debhelper devscripts fakeroot

      - name: Build
        run: dpkg-buildpackage -us -uc

      - name: Copy
        run: |
          mkdir output
          cp ../fy4dec_* output/
          cp ../fy4dec-dbgsym_* output/

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: fy4dec-debpkg-${{ matrix.distro }}
          path: output/
          if-no-files-found: error